name: tokio_marine
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-290.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    


  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  provider: ^6.0.5
  firebase_auth: ^4.2.9
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  webview_flutter: ^4.0.6
  http: ^0.13.5
  webview_flutter_android: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
   

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
