// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSTzox1NpyCqa5sO8SRArPAV7jaRxKQ3s',
    appId: '1:43474848615:web:deb8bb5d5237ae5ec53dc2',
    messagingSenderId: '43474848615',
    projectId: 'tokio-marine-desafio',
    authDomain: 'tokio-marine-desafio.firebaseapp.com',
    storageBucket: 'tokio-marine-desafio.appspot.com',
    measurementId: 'G-LPZ5HT1SMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMfIBRWGnu4HnqqBj3n5tB1K__rXrD47w',
    appId: '1:43474848615:android:c4cd779cd0600efec53dc2',
    messagingSenderId: '43474848615',
    projectId: 'tokio-marine-desafio',
    storageBucket: 'tokio-marine-desafio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmRO3EbY9SRoTtB9HXBJJJf7kxRtbKZag',
    appId: '1:43474848615:ios:b04558044652a164c53dc2',
    messagingSenderId: '43474848615',
    projectId: 'tokio-marine-desafio',
    storageBucket: 'tokio-marine-desafio.appspot.com',
    iosClientId: '43474848615-av6u72sahfa7kc8033sr520rau6t8jr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tokioMarine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmRO3EbY9SRoTtB9HXBJJJf7kxRtbKZag',
    appId: '1:43474848615:ios:c4dc0ff43989478ec53dc2',
    messagingSenderId: '43474848615',
    projectId: 'tokio-marine-desafio',
    storageBucket: 'tokio-marine-desafio.appspot.com',
    iosClientId: '43474848615-t2bj5cvcqvmkju9ptnqdsik4aahne3pe.apps.googleusercontent.com',
    iosBundleId: 'com.example.tokioMarine.RunnerTests',
  );
}
